CREATE DATABASE IF NOT EXISTS `beego_unit_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE beego_unit_test;

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
  `uid` BIGINT NOT NULL UNIQUE ,
  `username` VARCHAR(255) NOT NULL UNIQUE ,
  `password` VARCHAR(40) NOT NULL ,
  `nickname` VARCHAR(40) NOT NULL ,
  `token` VARCHAR(40) NOT NULL UNIQUE ,
  `phone` VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS `verification` (
  `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
  `phone` VARCHAR(11) NOT NULL UNIQUE ,
  `code` VARCHAR(6) NOT NULL ,
  `expire` BIGINT NOT NULL
);